# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20230725_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Writer'),
        ),
    ]
