# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('repassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning_logs.Writer'),
        ),
    ]
