# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-27 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20230727_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='repassword',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='register_writer',
            name='instroduction',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='register_writer',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='register_writer',
            name='password',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='register_writer',
            name='repassword',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='writer',
            name='instroduction',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='writer',
            name='password',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
