# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20230727_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(max_length=200, null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='writer',
            name='instroduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='writer',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='writer',
            name='repassword',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='writer',
            name='telephone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
