# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-27 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20230727_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='writer',
            new_name='lover',
        ),
    ]
